repos:
  - repo: local
    hooks:
      - id: spotless
        name: Spotless
        entry: mvn spotless:apply
        language: system
        files: \.java$

      - id: checkstyle
        name: Checkstyle
        entry: mvn checkstyle:check
        language: system
        files: \.java$

      - id: test
        name: Tests
        entry: mvn test
        language: system
        pass_filenames: false
        stages: [ pre-commit ]