name: Travel-Agency kata
run-name: Travel-Agency kata
on: [push]
jobs:
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Spotless
        run: mvn spotless:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t sergior00/travel-agency-kata:latest .
      - name: Login Docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - run: docker push sergior00/travel-agency-kata:latest
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}